/* THIS FILE IS GENERATED. DO NOT EDIT */
package org.jruby.gen;
import org.jruby.Ruby;
import org.jruby.RubyModule;
import org.jruby.RubyClass;
import org.jruby.CompatVersion;
import org.jruby.anno.TypePopulator;
import org.jruby.internal.runtime.methods.CallConfiguration;
import org.jruby.internal.runtime.methods.JavaMethod;
import org.jruby.internal.runtime.methods.DynamicMethod;
import org.jruby.runtime.Arity;
import org.jruby.runtime.Visibility;
import org.jruby.compiler.ASTInspector;
import java.util.Arrays;
import java.util.List;
public class org$jruby$ext$bigdecimal$RubyBigDecimal$POPULATOR extends TypePopulator {
    public void populate(RubyModule cls, Class clazz) {
        JavaMethod javaMethod;
        DynamicMethod moduleMethod;
        RubyClass singletonClass = cls.getSingletonClass();
        CompatVersion compatVersion = cls.getRuntime().getInstanceConfig().getCompatVersion();
        Ruby runtime = cls.getRuntime();
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$s$0$1$limit(singletonClass, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "limit", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "limit", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.builtin.IRubyObject[].class});
        singletonClass.addMethodAtBootTimeOnly("limit", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$s$0$0$save_rounding_mode(singletonClass, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "save_rounding_mode", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "save_rounding_mode", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.Block.class});
        singletonClass.addMethodAtBootTimeOnly("save_rounding_mode", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$s$0$1$newInstance(singletonClass, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "newInstance", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "newInstance", org.jruby.ext.bigdecimal.RubyBigDecimal.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.builtin.IRubyObject[].class});
        singletonClass.addMethodAtBootTimeOnly("new", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$s$0$0$double_fig(singletonClass, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "double_fig", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "double_fig", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        singletonClass.addMethodAtBootTimeOnly("double_fig", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$s$1$0$load(singletonClass, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "load", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "load", org.jruby.ext.bigdecimal.RubyBigDecimal.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.Block.class});
        singletonClass.addMethodAtBootTimeOnly("_load", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$s$1$0$induced_from(singletonClass, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "induced_from", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "induced_from", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.builtin.IRubyObject.class});
        singletonClass.addMethodAtBootTimeOnly("induced_from", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$s$0$0$ver(singletonClass, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "ver", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "ver", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        singletonClass.addMethodAtBootTimeOnly("ver", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$s$0$0$save_limit(singletonClass, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "save_limit", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "save_limit", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.Block.class});
        singletonClass.addMethodAtBootTimeOnly("save_limit", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$s$0$1$mode(singletonClass, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "mode", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "mode", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.builtin.IRubyObject[].class});
        singletonClass.addMethodAtBootTimeOnly("mode", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$s$0$0$save_exception_mode(singletonClass, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "save_exception_mode", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "save_exception_mode", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.Block.class});
        singletonClass.addMethodAtBootTimeOnly("save_exception_mode", javaMethod);
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","limit","limit");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","save_rounding_mode","save_rounding_mode");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","newInstance","new");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","double_fig","double_fig");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","load","_load");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","induced_from","induced_from");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","ver","ver");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","save_limit","save_limit");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","mode","mode");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","save_exception_mode","save_exception_mode");
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$to_f(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "to_f", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "to_f", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("to_f", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$2$0$sub2(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 2, "sub2", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "sub2", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("sub", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$2$0$mult2(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 2, "mult2", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "mult2", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("mult", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$1$ceil(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "ceil", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "ceil", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject[].class});
        cls.addMethodAtBootTimeOnly("ceil", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$nonzero_p(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "nonzero_p", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "nonzero_p", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("nonzero?", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$2$round(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "round", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "round", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject[].class});
        cls.addMethodAtBootTimeOnly("round", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$op_ge(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "op_ge", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_ge", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly(">=", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$2$0$add2(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 2, "add2", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "add2", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("add", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$1$to_s(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "to_s", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "to_s", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject[].class});
        cls.addMethodAtBootTimeOnly("to_s", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$op_cmp(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "op_cmp", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_cmp", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("<=>", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$remainder(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "remainder", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "remainder", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("remainder", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$1$dump(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "dump", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "dump", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject[].class, org.jruby.runtime.Block.class});
        cls.addMethodAtBootTimeOnly("_dump", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$abs(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "abs", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "abs", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("abs", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$nan_p(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "nan_p", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "nan_p", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("nan?", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$op_uminus(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "op_uminus", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_uminus", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("-@", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$coerce(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "coerce", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "coerce", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("coerce", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$hash(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "hash", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "hash", org.jruby.RubyFixnum.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("hash", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$exponent(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "exponent", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "exponent", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("exponent", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$sqrt(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "sqrt", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "sqrt", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("sqrt", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$fix(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "fix", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "fix", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("fix", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$op_uplus(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "op_uplus", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_uplus", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("+@", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$op_mul(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "op_mul", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_mul", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("*", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$op_plus(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "op_plus", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_plus", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("+", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$zero_p(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "zero_p", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "zero_p", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("zero?", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$op_minus(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "op_minus", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_minus", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("-", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$frac(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "frac", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "frac", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("frac", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$sign(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "sign", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "sign", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("sign", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$1$floor(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "floor", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "floor", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject[].class});
        cls.addMethodAtBootTimeOnly("floor", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$op_le(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "op_le", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_le", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("<=", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$split(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "split", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "split", org.jruby.RubyArray.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("split", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$eql_p(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "eql_p", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "eql_p", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("eql?", javaMethod);
        cls.addMethodAtBootTimeOnly("==", javaMethod);
        cls.addMethodAtBootTimeOnly("===", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$op_gt(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "op_gt", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_gt", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly(">", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$inspect(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "inspect", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "inspect", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("inspect", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$finite_p(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "finite_p", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "finite_p", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("finite?", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$precs(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "precs", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "precs", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("precs", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$op_lt(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "op_lt", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_lt", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("<", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$infinite_p(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "infinite_p", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "infinite_p", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("infinite?", javaMethod);
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","to_f","to_f");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","sub2","sub");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","mult2","mult");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","ceil","ceil");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","nonzero_p","nonzero?");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","round","round");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_ge",">=");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","add2","add");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","to_s","to_s");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_cmp","<=>");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","remainder","remainder");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","dump","_dump");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","abs","abs");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","nan_p","nan?");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_uminus","-@");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","coerce","coerce");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","hash","hash");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","exponent","exponent");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","sqrt","sqrt");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","fix","fix");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_uplus","+@");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_mul","*");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_plus","+");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","zero_p","zero?");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_minus","-");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","frac","frac");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","sign","sign");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","floor","floor");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_le","<=");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","split","split");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","eql_p","eql?");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_gt",">");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","inspect","inspect");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","finite_p","finite?");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","precs","precs");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_lt","<");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","infinite_p","infinite?");
        if (compatVersion == CompatVersion.RUBY1_8 || compatVersion == CompatVersion.BOTH) {
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$to_int(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "to_int", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "to_int", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("to_i", javaMethod);
        cls.addMethodAtBootTimeOnly("to_int", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$1$truncate(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "truncate", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "truncate", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject[].class});
        cls.addMethodAtBootTimeOnly("truncate", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$divmod(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "divmod", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "divmod", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("divmod", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$op_mod(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "op_mod", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_mod", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("%", javaMethod);
        cls.addMethodAtBootTimeOnly("modulo", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$op_div(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "op_div", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_div", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("div", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$op_quo(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "op_quo", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_quo", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("/", javaMethod);
        cls.addMethodAtBootTimeOnly("quo", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$op_pow(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "op_pow", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_pow", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("**", javaMethod);
        cls.addMethodAtBootTimeOnly("power", javaMethod);
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","to_int","to_i");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","truncate","truncate");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","divmod","divmod");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_mod","%");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_div","div");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_quo","/");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_pow","**");
        }
        if (compatVersion.is1_9() || compatVersion == CompatVersion.BOTH) {
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$1$floor19(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "floor19", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "floor19", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject[].class});
        cls.addMethodAtBootTimeOnly("floor", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$0$to_int19(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "to_int19", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "to_int19", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("to_i", javaMethod);
        cls.addMethodAtBootTimeOnly("to_int", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$1$truncate19(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "truncate19", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "truncate19", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject[].class});
        cls.addMethodAtBootTimeOnly("truncate", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$divmod19(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "divmod19", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "divmod19", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("divmod", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$0$1$ceil19(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "ceil19", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "ceil19", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject[].class});
        cls.addMethodAtBootTimeOnly("ceil", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$op_mod19(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "op_mod19", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_mod19", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("%", javaMethod);
        cls.addMethodAtBootTimeOnly("modulo", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$op_div19(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "op_div19", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_div19", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("div", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$op_quo19(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "op_quo19", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_quo19", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("/", javaMethod);
        cls.addMethodAtBootTimeOnly("quo", javaMethod);
        javaMethod = new org.jruby.ext.bigdecimal.RubyBigDecimal$INVOKER$i$1$0$op_pow19(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "op_pow19", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.bigdecimal.RubyBigDecimal.class, "op_pow19", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("**", javaMethod);
        cls.addMethodAtBootTimeOnly("power", javaMethod);
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","floor19","floor");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","to_int19","to_i");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","truncate19","truncate");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","divmod19","divmod");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","ceil19","ceil");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_mod19","%");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_div19","div");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_quo19","/");
        runtime.addBoundMethod("org.jruby.ext.bigdecimal.RubyBigDecimal","op_pow19","**");
        }
    }
    static {
     }
}
