/* THIS FILE IS GENERATED. DO NOT EDIT */
package org.jruby.gen;
import org.jruby.Ruby;
import org.jruby.RubyModule;
import org.jruby.RubyClass;
import org.jruby.CompatVersion;
import org.jruby.anno.TypePopulator;
import org.jruby.internal.runtime.methods.CallConfiguration;
import org.jruby.internal.runtime.methods.JavaMethod;
import org.jruby.internal.runtime.methods.DynamicMethod;
import org.jruby.runtime.Arity;
import org.jruby.runtime.Visibility;
import org.jruby.compiler.ASTInspector;
import java.util.Arrays;
import java.util.List;
public class org$jruby$ext$openssl$PKeyDH$POPULATOR extends TypePopulator {
    public void populate(RubyModule cls, Class clazz) {
        JavaMethod javaMethod;
        DynamicMethod moduleMethod;
        Ruby runtime = cls.getRuntime();
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$0$0$dh_get_g(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "dh_get_g", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_get_g", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("g", javaMethod);
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$0$0$dh_export(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "dh_export", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_export", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("export", javaMethod);
        cls.addMethodAtBootTimeOnly("to_pem", javaMethod);
        cls.addMethodAtBootTimeOnly("to_s", javaMethod);
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$1$0$dh_set_g(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "dh_set_g", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_set_g", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("g=", javaMethod);
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$1$0$dh_set_p(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "dh_set_p", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_set_p", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("p=", javaMethod);
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$0$0$dh_to_der(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "dh_to_der", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_to_der", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("to_der", javaMethod);
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$0$0$dh_get_params(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "dh_get_params", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_get_params", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("params", javaMethod);
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$1$0$dh_set_pub_key(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "dh_set_pub_key", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_set_pub_key", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("pub_key=", javaMethod);
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$1$0$dh_compute_key(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "dh_compute_key", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_compute_key", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("compute_key", javaMethod);
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$1$0$dh_set_priv_key(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "dh_set_priv_key", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_set_priv_key", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("priv_key=", javaMethod);
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$0$0$dh_is_public(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "dh_is_public", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_is_public", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("public?", javaMethod);
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$0$0$dh_get_priv_key(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "dh_get_priv_key", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_get_priv_key", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("priv_key", javaMethod);
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$0$0$dh_get_p(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "dh_get_p", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_get_p", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("p", javaMethod);
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$0$0$dh_initialize(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "dh_initialize", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_initialize", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject[].class});
        cls.addMethodAtBootTimeOnly("initialize", javaMethod);
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$0$0$dh_generate_key(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "dh_generate_key", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_generate_key", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("generate_key!", javaMethod);
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$0$0$dh_is_private(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "dh_is_private", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_is_private", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("private?", javaMethod);
        javaMethod = new org.jruby.ext.openssl.PKeyDH$INVOKER$i$0$0$dh_get_pub_key(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "dh_get_pub_key", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.PKeyDH.class, "dh_get_pub_key", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("pub_key", javaMethod);
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_get_g","g");
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_export","export");
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_set_g","g=");
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_set_p","p=");
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_to_der","to_der");
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_get_params","params");
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_set_pub_key","pub_key=");
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_compute_key","compute_key");
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_set_priv_key","priv_key=");
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_is_public","public?");
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_get_priv_key","priv_key");
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_get_p","p");
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_initialize","initialize");
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_generate_key","generate_key!");
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_is_private","private?");
        runtime.addBoundMethod("org.jruby.ext.openssl.PKeyDH","dh_get_pub_key","pub_key");
    }
    static {
     }
}
