/* THIS FILE IS GENERATED. DO NOT EDIT */
package org.jruby.gen;
import org.jruby.Ruby;
import org.jruby.RubyModule;
import org.jruby.RubyClass;
import org.jruby.CompatVersion;
import org.jruby.anno.TypePopulator;
import org.jruby.internal.runtime.methods.CallConfiguration;
import org.jruby.internal.runtime.methods.JavaMethod;
import org.jruby.internal.runtime.methods.DynamicMethod;
import org.jruby.runtime.Arity;
import org.jruby.runtime.Visibility;
import org.jruby.compiler.ASTInspector;
import java.util.Arrays;
import java.util.List;
public class org$jruby$RubyNumeric$POPULATOR extends TypePopulator {
    public void populate(RubyModule cls, Class clazz) {
        JavaMethod javaMethod;
        DynamicMethod moduleMethod;
        CompatVersion compatVersion = cls.getRuntime().getInstanceConfig().getCompatVersion();
        Ruby runtime = cls.getRuntime();
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$op_uminus(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "op_uminus", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "op_uminus", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("-@", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$1$0$coerce(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "coerce", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "coerce", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("coerce", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$ceil(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "ceil", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "ceil", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("ceil", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$nonzero_p(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "nonzero_p", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "nonzero_p", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("nonzero?", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$op_uplus(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "op_uplus", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "op_uplus", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("+@", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$round(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "round", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "round", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("round", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$1$0$initialize_copy(cls, Visibility.PRIVATE);
        populateMethod(javaMethod, 1, "initialize_copy", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "initialize_copy", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("initialize_copy", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$zero_p(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "zero_p", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "zero_p", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("zero?", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$1$0$sadded(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "sadded", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "sadded", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("singleton_method_added", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$1$0$op_cmp(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "op_cmp", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "op_cmp", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("<=>", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$1$0$remainder(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "remainder", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "remainder", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("remainder", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$to_int(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "to_int", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "to_int", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("to_int", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$abs(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "abs", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "abs", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("abs", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$floor(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "floor", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "floor", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("floor", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$integer_p(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "integer_p", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "integer_p", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("integer?", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$truncate(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "truncate", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "truncate", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("truncate", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$step(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "step", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "step", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.Block.class});
        cls.addMethodAtBootTimeOnly("step", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$1$0$eql_p(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "eql_p", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "eql_p", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("eql?", javaMethod);
        runtime.addBoundMethod("org.jruby.RubyNumeric","op_uminus","-@");
        runtime.addBoundMethod("org.jruby.RubyNumeric","coerce","coerce");
        runtime.addBoundMethod("org.jruby.RubyNumeric","ceil","ceil");
        runtime.addBoundMethod("org.jruby.RubyNumeric","nonzero_p","nonzero?");
        runtime.addBoundMethod("org.jruby.RubyNumeric","op_uplus","+@");
        runtime.addBoundMethod("org.jruby.RubyNumeric","round","round");
        runtime.addBoundMethod("org.jruby.RubyNumeric","initialize_copy","initialize_copy");
        runtime.addBoundMethod("org.jruby.RubyNumeric","zero_p","zero?");
        runtime.addBoundMethod("org.jruby.RubyNumeric","sadded","singleton_method_added");
        runtime.addBoundMethod("org.jruby.RubyNumeric","op_cmp","<=>");
        runtime.addBoundMethod("org.jruby.RubyNumeric","remainder","remainder");
        runtime.addBoundMethod("org.jruby.RubyNumeric","to_int","to_int");
        runtime.addBoundMethod("org.jruby.RubyNumeric","abs","abs");
        runtime.addBoundMethod("org.jruby.RubyNumeric","floor","floor");
        runtime.addBoundMethod("org.jruby.RubyNumeric","integer_p","integer?");
        runtime.addBoundMethod("org.jruby.RubyNumeric","truncate","truncate");
        runtime.addBoundMethod("org.jruby.RubyNumeric","step","step");
        runtime.addBoundMethod("org.jruby.RubyNumeric","eql_p","eql?");
        if (compatVersion == CompatVersion.RUBY1_8 || compatVersion == CompatVersion.BOTH) {
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$1$0$quo(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "quo", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "quo", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("quo", javaMethod);
        cls.addMethodAtBootTimeOnly("fdiv", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$1$0$divmod(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "divmod", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "divmod", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("divmod", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$1$0$div(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "div", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "div", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("div", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$1$0$modulo(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "modulo", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "modulo", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("modulo", javaMethod);
        runtime.addBoundMethod("org.jruby.RubyNumeric","quo","quo");
        runtime.addBoundMethod("org.jruby.RubyNumeric","divmod","divmod");
        runtime.addBoundMethod("org.jruby.RubyNumeric","div","div");
        runtime.addBoundMethod("org.jruby.RubyNumeric","modulo","modulo");
        }
        if (compatVersion.is1_9() || compatVersion == CompatVersion.BOTH) {
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$polar(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "polar", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "polar", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("polar", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$rect(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "rect", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "rect", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("rectangular", javaMethod);
        cls.addMethodAtBootTimeOnly("rect", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$1$0$divmod19(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "divmod19", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "divmod19", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("divmod", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$1$0$div19(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "div19", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "div19", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("div", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$magnitude(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "magnitude", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "magnitude", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("magnitude", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$numerator(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "numerator", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "numerator", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("numerator", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$denominator(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "denominator", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "denominator", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("denominator", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$image(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "image", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "image", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("imaginary", javaMethod);
        cls.addMethodAtBootTimeOnly("imag", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$conjugate(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "conjugate", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "conjugate", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("conjugate", javaMethod);
        cls.addMethodAtBootTimeOnly("conj", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$num_imaginary(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "num_imaginary", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "num_imaginary", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("i", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$1$0$quo_19(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "quo_19", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "quo_19", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("quo", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$arg(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "arg", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "arg", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("arg", javaMethod);
        cls.addMethodAtBootTimeOnly("angle", javaMethod);
        cls.addMethodAtBootTimeOnly("phase", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$real(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "real", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "real", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("real", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$scalar_p(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "scalar_p", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "scalar_p", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("real?", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$1$0$modulo19(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "modulo19", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "modulo19", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("modulo", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$to_c(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "to_c", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "to_c", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("to_c", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$0$0$abs2(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "abs2", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "abs2", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class});
        cls.addMethodAtBootTimeOnly("abs2", javaMethod);
        javaMethod = new org.jruby.RubyNumeric$INVOKER$i$1$0$fdiv(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "fdiv", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.RubyNumeric.class, "fdiv", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("fdiv", javaMethod);
        runtime.addBoundMethod("org.jruby.RubyNumeric","polar","polar");
        runtime.addBoundMethod("org.jruby.RubyNumeric","rect","rectangular");
        runtime.addBoundMethod("org.jruby.RubyNumeric","divmod19","divmod");
        runtime.addBoundMethod("org.jruby.RubyNumeric","div19","div");
        runtime.addBoundMethod("org.jruby.RubyNumeric","magnitude","magnitude");
        runtime.addBoundMethod("org.jruby.RubyNumeric","numerator","numerator");
        runtime.addBoundMethod("org.jruby.RubyNumeric","denominator","denominator");
        runtime.addBoundMethod("org.jruby.RubyNumeric","image","imaginary");
        runtime.addBoundMethod("org.jruby.RubyNumeric","conjugate","conjugate");
        runtime.addBoundMethod("org.jruby.RubyNumeric","num_imaginary","i");
        runtime.addBoundMethod("org.jruby.RubyNumeric","quo_19","quo");
        runtime.addBoundMethod("org.jruby.RubyNumeric","arg","arg");
        runtime.addBoundMethod("org.jruby.RubyNumeric","real","real");
        runtime.addBoundMethod("org.jruby.RubyNumeric","scalar_p","real?");
        runtime.addBoundMethod("org.jruby.RubyNumeric","modulo19","modulo");
        runtime.addBoundMethod("org.jruby.RubyNumeric","to_c","to_c");
        runtime.addBoundMethod("org.jruby.RubyNumeric","abs2","abs2");
        runtime.addBoundMethod("org.jruby.RubyNumeric","fdiv","fdiv");
        }
    }
    static {
     }
}
