/* THIS FILE IS GENERATED. DO NOT EDIT */
package org.jruby.gen;
import org.jruby.Ruby;
import org.jruby.RubyModule;
import org.jruby.RubyClass;
import org.jruby.CompatVersion;
import org.jruby.anno.TypePopulator;
import org.jruby.internal.runtime.methods.CallConfiguration;
import org.jruby.internal.runtime.methods.JavaMethod;
import org.jruby.internal.runtime.methods.DynamicMethod;
import org.jruby.runtime.Arity;
import org.jruby.runtime.Visibility;
import org.jruby.compiler.ASTInspector;
import java.util.Arrays;
import java.util.List;
public class org$jruby$ext$openssl$X509StoreCtx$POPULATOR extends TypePopulator {
    public void populate(RubyModule cls, Class clazz) {
        JavaMethod javaMethod;
        DynamicMethod moduleMethod;
        Ruby runtime = cls.getRuntime();
        javaMethod = new org.jruby.ext.openssl.X509StoreCtx$INVOKER$i$0$0$chain(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "chain", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509StoreCtx.class, "chain", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("chain", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509StoreCtx$INVOKER$i$0$0$verify(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "verify", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509StoreCtx.class, "verify", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("verify", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509StoreCtx$INVOKER$i$1$0$set_time(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "set_time", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509StoreCtx.class, "set_time", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("time=", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509StoreCtx$INVOKER$i$0$0$error_string(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "error_string", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509StoreCtx.class, "error_string", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("error_string", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509StoreCtx$INVOKER$i$1$0$set_error(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "set_error", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509StoreCtx.class, "set_error", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("error=", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509StoreCtx$INVOKER$i$0$0$error_depth(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "error_depth", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509StoreCtx.class, "error_depth", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("error_depth", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509StoreCtx$INVOKER$i$1$0$set_flags(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "set_flags", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509StoreCtx.class, "set_flags", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("flags=", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509StoreCtx$INVOKER$i$0$0$cleanup(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "cleanup", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509StoreCtx.class, "cleanup", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("cleanup", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509StoreCtx$INVOKER$i$1$0$set_trust(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "set_trust", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509StoreCtx.class, "set_trust", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("trust=", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509StoreCtx$INVOKER$i$0$0$current_cert(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "current_cert", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509StoreCtx.class, "current_cert", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("current_cert", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509StoreCtx$INVOKER$i$1$0$set_purpose(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "set_purpose", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509StoreCtx.class, "set_purpose", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("purpose=", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509StoreCtx$INVOKER$i$0$0$error(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "error", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509StoreCtx.class, "error", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("error", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509StoreCtx$INVOKER$i$0$0$current_crl(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "current_crl", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509StoreCtx.class, "current_crl", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("current_crl", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509StoreCtx$INVOKER$i$0$0$_initialize(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "_initialize", false, CallConfiguration.FrameFullScopeNone, false, org.jruby.ext.openssl.X509StoreCtx.class, "_initialize", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject[].class, org.jruby.runtime.Block.class});
        cls.addMethodAtBootTimeOnly("initialize", javaMethod);
        runtime.addBoundMethod("org.jruby.ext.openssl.X509StoreCtx","chain","chain");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509StoreCtx","verify","verify");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509StoreCtx","set_time","time=");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509StoreCtx","error_string","error_string");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509StoreCtx","set_error","error=");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509StoreCtx","error_depth","error_depth");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509StoreCtx","set_flags","flags=");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509StoreCtx","cleanup","cleanup");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509StoreCtx","set_trust","trust=");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509StoreCtx","current_cert","current_cert");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509StoreCtx","set_purpose","purpose=");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509StoreCtx","error","error");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509StoreCtx","current_crl","current_crl");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509StoreCtx","_initialize","initialize");
    }
    static {
        ASTInspector.addFrameAwareMethods("initialize");
     }
}
