/* THIS FILE IS GENERATED. DO NOT EDIT */
package org.jruby.gen;
import org.jruby.Ruby;
import org.jruby.RubyModule;
import org.jruby.RubyClass;
import org.jruby.CompatVersion;
import org.jruby.anno.TypePopulator;
import org.jruby.internal.runtime.methods.CallConfiguration;
import org.jruby.internal.runtime.methods.JavaMethod;
import org.jruby.internal.runtime.methods.DynamicMethod;
import org.jruby.runtime.Arity;
import org.jruby.runtime.Visibility;
import org.jruby.compiler.ASTInspector;
import java.util.Arrays;
import java.util.List;
public class org$jruby$ext$etc$RubyEtc$POPULATOR extends TypePopulator {
    public void populate(RubyModule cls, Class clazz) {
        JavaMethod javaMethod;
        DynamicMethod moduleMethod;
        RubyClass singletonClass = cls.getSingletonClass();
        CompatVersion compatVersion = cls.getRuntime().getInstanceConfig().getCompatVersion();
        Ruby runtime = cls.getRuntime();
        javaMethod = new org.jruby.ext.etc.RubyEtc$INVOKER$s$0$0$group(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "group", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.etc.RubyEtc.class, "group", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.Block.class});
        cls.addMethodAtBootTimeOnly("group", javaMethod);
        moduleMethod = populateModuleMethod(cls, javaMethod);
        singletonClass.addMethodAtBootTimeOnly("group", moduleMethod);
        javaMethod = new org.jruby.ext.etc.RubyEtc$INVOKER$s$0$0$getpwent(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "getpwent", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.etc.RubyEtc.class, "getpwent", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("getpwent", javaMethod);
        moduleMethod = populateModuleMethod(cls, javaMethod);
        singletonClass.addMethodAtBootTimeOnly("getpwent", moduleMethod);
        javaMethod = new org.jruby.ext.etc.RubyEtc$INVOKER$s$0$0$setpwent(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "setpwent", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.etc.RubyEtc.class, "setpwent", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("setpwent", javaMethod);
        moduleMethod = populateModuleMethod(cls, javaMethod);
        singletonClass.addMethodAtBootTimeOnly("setpwent", moduleMethod);
        javaMethod = new org.jruby.ext.etc.RubyEtc$INVOKER$s$0$0$getlogin(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "getlogin", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.etc.RubyEtc.class, "getlogin", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("getlogin", javaMethod);
        moduleMethod = populateModuleMethod(cls, javaMethod);
        singletonClass.addMethodAtBootTimeOnly("getlogin", moduleMethod);
        javaMethod = new org.jruby.ext.etc.RubyEtc$INVOKER$s$0$0$getgrent(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "getgrent", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.etc.RubyEtc.class, "getgrent", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("getgrent", javaMethod);
        moduleMethod = populateModuleMethod(cls, javaMethod);
        singletonClass.addMethodAtBootTimeOnly("getgrent", moduleMethod);
        javaMethod = new org.jruby.ext.etc.RubyEtc$INVOKER$s$0$0$passwd(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "passwd", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.etc.RubyEtc.class, "passwd", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.Block.class});
        cls.addMethodAtBootTimeOnly("passwd", javaMethod);
        moduleMethod = populateModuleMethod(cls, javaMethod);
        singletonClass.addMethodAtBootTimeOnly("passwd", moduleMethod);
        javaMethod = new org.jruby.ext.etc.RubyEtc$INVOKER$s$0$1$getgrgid(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "getgrgid", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.etc.RubyEtc.class, "getgrgid", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.builtin.IRubyObject[].class});
        cls.addMethodAtBootTimeOnly("getgrgid", javaMethod);
        moduleMethod = populateModuleMethod(cls, javaMethod);
        singletonClass.addMethodAtBootTimeOnly("getgrgid", moduleMethod);
        javaMethod = new org.jruby.ext.etc.RubyEtc$INVOKER$s$0$0$endgrent(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "endgrent", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.etc.RubyEtc.class, "endgrent", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("endgrent", javaMethod);
        moduleMethod = populateModuleMethod(cls, javaMethod);
        singletonClass.addMethodAtBootTimeOnly("endgrent", moduleMethod);
        javaMethod = new org.jruby.ext.etc.RubyEtc$INVOKER$s$0$0$setgrent(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "setgrent", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.etc.RubyEtc.class, "setgrent", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("setgrent", javaMethod);
        moduleMethod = populateModuleMethod(cls, javaMethod);
        singletonClass.addMethodAtBootTimeOnly("setgrent", moduleMethod);
        javaMethod = new org.jruby.ext.etc.RubyEtc$INVOKER$s$1$0$getgrnam(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "getgrnam", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.etc.RubyEtc.class, "getgrnam", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("getgrnam", javaMethod);
        moduleMethod = populateModuleMethod(cls, javaMethod);
        singletonClass.addMethodAtBootTimeOnly("getgrnam", moduleMethod);
        javaMethod = new org.jruby.ext.etc.RubyEtc$INVOKER$s$0$1$getpwuid(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "getpwuid", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.etc.RubyEtc.class, "getpwuid", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.builtin.IRubyObject[].class});
        cls.addMethodAtBootTimeOnly("getpwuid", javaMethod);
        moduleMethod = populateModuleMethod(cls, javaMethod);
        singletonClass.addMethodAtBootTimeOnly("getpwuid", moduleMethod);
        javaMethod = new org.jruby.ext.etc.RubyEtc$INVOKER$s$1$0$getpwnam(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "getpwnam", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.etc.RubyEtc.class, "getpwnam", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("getpwnam", javaMethod);
        moduleMethod = populateModuleMethod(cls, javaMethod);
        singletonClass.addMethodAtBootTimeOnly("getpwnam", moduleMethod);
        javaMethod = new org.jruby.ext.etc.RubyEtc$INVOKER$s$0$0$endpwent(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "endpwent", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.etc.RubyEtc.class, "endpwent", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("endpwent", javaMethod);
        moduleMethod = populateModuleMethod(cls, javaMethod);
        singletonClass.addMethodAtBootTimeOnly("endpwent", moduleMethod);
        runtime.addBoundMethod("org.jruby.ext.etc.RubyEtc","group","group");
        runtime.addBoundMethod("org.jruby.ext.etc.RubyEtc","getpwent","getpwent");
        runtime.addBoundMethod("org.jruby.ext.etc.RubyEtc","setpwent","setpwent");
        runtime.addBoundMethod("org.jruby.ext.etc.RubyEtc","getlogin","getlogin");
        runtime.addBoundMethod("org.jruby.ext.etc.RubyEtc","getgrent","getgrent");
        runtime.addBoundMethod("org.jruby.ext.etc.RubyEtc","passwd","passwd");
        runtime.addBoundMethod("org.jruby.ext.etc.RubyEtc","getgrgid","getgrgid");
        runtime.addBoundMethod("org.jruby.ext.etc.RubyEtc","endgrent","endgrent");
        runtime.addBoundMethod("org.jruby.ext.etc.RubyEtc","setgrent","setgrent");
        runtime.addBoundMethod("org.jruby.ext.etc.RubyEtc","getgrnam","getgrnam");
        runtime.addBoundMethod("org.jruby.ext.etc.RubyEtc","getpwuid","getpwuid");
        runtime.addBoundMethod("org.jruby.ext.etc.RubyEtc","getpwnam","getpwnam");
        runtime.addBoundMethod("org.jruby.ext.etc.RubyEtc","endpwent","endpwent");
        if (compatVersion.is1_9() || compatVersion == CompatVersion.BOTH) {
        javaMethod = new org.jruby.ext.etc.RubyEtc$INVOKER$s$0$0$sysconfdir(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "sysconfdir", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.etc.RubyEtc.class, "sysconfdir", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("sysconfdir", javaMethod);
        moduleMethod = populateModuleMethod(cls, javaMethod);
        singletonClass.addMethodAtBootTimeOnly("sysconfdir", moduleMethod);
        javaMethod = new org.jruby.ext.etc.RubyEtc$INVOKER$s$0$0$systmpdir(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "systmpdir", true, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.etc.RubyEtc.class, "systmpdir", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.ThreadContext.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("systmpdir", javaMethod);
        moduleMethod = populateModuleMethod(cls, javaMethod);
        singletonClass.addMethodAtBootTimeOnly("systmpdir", moduleMethod);
        runtime.addBoundMethod("org.jruby.ext.etc.RubyEtc","sysconfdir","sysconfdir");
        runtime.addBoundMethod("org.jruby.ext.etc.RubyEtc","systmpdir","systmpdir");
        }
    }
    static {
     }
}
