/* THIS FILE IS GENERATED. DO NOT EDIT */
package org.jruby.gen;
import org.jruby.Ruby;
import org.jruby.RubyModule;
import org.jruby.RubyClass;
import org.jruby.CompatVersion;
import org.jruby.anno.TypePopulator;
import org.jruby.internal.runtime.methods.CallConfiguration;
import org.jruby.internal.runtime.methods.JavaMethod;
import org.jruby.internal.runtime.methods.DynamicMethod;
import org.jruby.runtime.Arity;
import org.jruby.runtime.Visibility;
import org.jruby.compiler.ASTInspector;
import java.util.Arrays;
import java.util.List;
public class org$jruby$ext$openssl$X509CRL$POPULATOR extends TypePopulator {
    public void populate(RubyModule cls, Class clazz) {
        JavaMethod javaMethod;
        DynamicMethod moduleMethod;
        Ruby runtime = cls.getRuntime();
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$1$0$set_next_update(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "set_next_update", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "set_next_update", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("next_update=", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$1$0$set_version(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "set_version", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "set_version", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("version=", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$1$0$add_revoked(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "add_revoked", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "add_revoked", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("add_revoked", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$0$0$extensions(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "extensions", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "extensions", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("extensions", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$1$0$verify(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "verify", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "verify", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("verify", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$2$0$sign(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 2, "sign", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "sign", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class, org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("sign", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$0$0$next_update(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "next_update", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "next_update", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("next_update", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$1$0$set_extensions(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "set_extensions", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "set_extensions", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("extensions=", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$0$0$to_text(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "to_text", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "to_text", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("to_text", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$0$0$revoked(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "revoked", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "revoked", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("revoked", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$0$0$to_pem(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "to_pem", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "to_pem", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("to_pem", javaMethod);
        cls.addMethodAtBootTimeOnly("to_s", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$0$0$signature_algorithm(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "signature_algorithm", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "signature_algorithm", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("signature_algorithm", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$1$0$set_revoked(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "set_revoked", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "set_revoked", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("revoked=", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$0$0$version(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "version", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "version", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("version", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$0$0$issuer(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "issuer", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "issuer", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("issuer", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$1$0$initialize_copy(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "initialize_copy", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "initialize_copy", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("initialize_copy", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$0$0$last_update(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "last_update", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "last_update", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("last_update", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$1$0$set_last_update(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "set_last_update", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "set_last_update", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("last_update=", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$1$0$set_issuer(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "set_issuer", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "set_issuer", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("issuer=", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$1$0$add_extension(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 1, "add_extension", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "add_extension", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject.class});
        cls.addMethodAtBootTimeOnly("add_extension", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$0$0$to_der(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, 0, "to_der", false, CallConfiguration.FrameNoneScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "to_der", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {});
        cls.addMethodAtBootTimeOnly("to_der", javaMethod);
        javaMethod = new org.jruby.ext.openssl.X509CRL$INVOKER$i$0$0$_initialize(cls, Visibility.PUBLIC);
        populateMethod(javaMethod, -1, "_initialize", false, CallConfiguration.FrameFullScopeNone, false, org.jruby.ext.openssl.X509CRL.class, "_initialize", org.jruby.runtime.builtin.IRubyObject.class, new Class[] {org.jruby.runtime.builtin.IRubyObject[].class, org.jruby.runtime.Block.class});
        cls.addMethodAtBootTimeOnly("initialize", javaMethod);
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","set_next_update","next_update=");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","set_version","version=");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","add_revoked","add_revoked");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","extensions","extensions");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","verify","verify");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","sign","sign");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","next_update","next_update");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","set_extensions","extensions=");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","to_text","to_text");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","revoked","revoked");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","to_pem","to_pem");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","signature_algorithm","signature_algorithm");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","set_revoked","revoked=");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","version","version");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","issuer","issuer");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","initialize_copy","initialize_copy");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","last_update","last_update");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","set_last_update","last_update=");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","set_issuer","issuer=");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","add_extension","add_extension");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","to_der","to_der");
        runtime.addBoundMethod("org.jruby.ext.openssl.X509CRL","_initialize","initialize");
    }
    static {
        ASTInspector.addFrameAwareMethods("initialize");
     }
}
